[package]
name = "AsyncDB"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
bytes = "1.10.1"
thiserror = "2.0.16"
tokio = {version = "1.47.1" , features = ["full"]}
tokio-util = {version = "0.7.16", features = ["codec"]}
